Add optional command wrapper
jfpedroza/neotest-elixir pull request #22
Opened 2023-01-30 17:50 UTC by soundmonster

This allows mangling the Mix command at runtime, useful when env vars have to be set before running Mix, or some other
manipulation is required. I am using this to set environment variables to dynamic values based on `docker ps` output.

2023-01-31 09:02 UTC, jfpedroza requested changes
Thanks for the PR :)

2023-01-31 09:02 UTC, jfpedroza commented on README.md
> +      post_process_cmd = function()
The code says the option is called `post_process_command`.

2023-01-31 09:02 UTC, jfpedroza commented on lua/neotest-elixir/init.lua
> +      or vim.startswith(rel_path, "test/")
My formatter doesn't move this. Are you using a something different to stylua?

2023-01-31 09:02 UTC, jfpedroza commented on lua/neotest-elixir/init.lua
> +    local post_process_command = callable_opt(opts.post_process_command)
I don't think we need to use this. If the value is always a function, we don't need to wrap it in another.

2023-01-31 20:58 UTC, soundmonster commented on lua/neotest-elixir/init.lua
> +      or vim.startswith(rel_path, "test/")
thank you for pointing me to this; I've ran `stylua` manually and the format reverted back. I'll fix my setup.

2023-01-31 20:58 UTC, soundmonster commented on lua/neotest-elixir/init.lua
> +    local post_process_command = callable_opt(opts.post_process_command)
You are right, and now I think I've figured it out.

2023-01-31 20:59 UTC, soundmonster commented
Thank you very much for the review! I've tried to address the issues you've raised.

2023-02-03 05:49 UTC, jfpedroza approved these changes

2023-02-03 05:50 UTC, merged